version: '3'

networks:
  address-book-network:
    driver: bridge

volumes:
  address-book-elasticsearch-volume:
  solr-address-book:

services:
  address-book:
    container_name: address-book
    # image: node:18-alpine
    build: .
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - PORT=3024
      - NODE_ENV=development
      - CONFIG_PATH=config.json
    ports:
      - '3024:3024'
    depends_on:
      address-book-elasticsearch:
        condition: service_healthy
      address-book-solr:
        condition: service_healthy
    command: [ "npm", "run", "start" ]
    networks:
      - address-book-network

  address-book-elasticsearch:
    container_name: address-book-elasticsearch
    image: bitnami/elasticsearch:latest
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ELASTICSEARCH_NODE_NAME=elastic
      - BITNAMI_DEBUG=true
    ports:
      - '9200:9200'
    healthcheck:
      test: curl -u elastic:elastic -s -f http://address-book-elasticsearch:9200/_cat/health >/dev/null || exit 1
      timeout: 5s
      interval: 10s
      retries: 5
    volumes:
      - address-book-elasticsearch-volume:/usr/share/elasticsearch/data
    networks:
      - address-book-network

  address-book-kibana:
    container_name: address-book-kibana
    image: bitnami/kibana:latest
    ports:
      - '5601:5601'
    depends_on:
      address-book-elasticsearch:
        condition: service_healthy
    environment:
      - KIBANA_ELASTICSEARCH_URL=http://address-book-elasticsearch:9200
    networks:
      - address-book-network

  address-book-solr:
    container_name: address-book-solr
    build:
      context: .
      dockerfile: migration-scripts/Dockerfile
    ports:
      - '8983:8983'
    healthcheck:
      test: curl -u solr:solr -s -f address-book-solr:8983/solr/shaq/admin/ping >/dev/null || exit 1
      timeout: 5s
      interval: 15s
      retries: 10
    networks:
      - address-book-network
    volumes:
      - solr-address-book:/var/solr
